### ISSUE TITLE
feature question

### ISSUE THREAD

**Issue by curtiola** [Al-th/Vocals#14]
Hello,

First and foremost, I would like to thank you for Vocals. Seriously, it's awesome.

I was wondering, do you plan to implement exporting/importing profiles so we can share them, or is the profiles.vd file the equivalent of exporting a profile?

**Comment by Al-th** [comment]
Hey curtiola,

You can share the profile_xml.vc file as it is a plain text xml file that stores the profiles that you have in Vocals.

Best

**Comment by curtiola** [comment]
ok thanks for the quick response :)
