### ISSUE TITLE
[Feature request] configurable level of confidence to trigger

### ISSUE THREAD

**Issue by Geobert** [Al-th/Vocals#2]
Ce serait chouette de définir un niveau à partir duquel on trig la commande, j'ai beaucoup de faut positifs qui triggent à 0.73 par exemple (discussion dans la pièce)

**Comment by Al-th** [comment]
@Geobert : Si tu vas dans "Advanced settings", (bouton pas très visible je te l'accorde), au dessus du cadre de "profil", tu as la possibilité de changer le niveau d'activation de la reconnaissance ! 
Amicalement

**Comment by Geobert** [comment]
Oh super ! je vais tester ça ! du coup, la feature request pourrait devenir un override par rapport au setting global :)
