### ISSUE TITLE
Question. Feature proposal.

### ISSUE THREAD

**Issue by Forsaken-Player** [Al-th/Vocals#20]
Hi, I'm looking for some software that would press a key (joystick button, mouse or keyboard) while I talk and find this nice program!!! I need this features so that I could use "voice activated voice chat". One example for this is the game Squad where there no voice activation.

Thank you very much for reading!

PS.: Sorry about my English, it may sound weird.. :D

**Comment by Al-th** [comment]
Hello,

I do not get exactly your question. This piece of software is doing exactly what you are requesting, insn't it ?

**Comment by Forsaken-Player** [comment]
It doesn't do exactly what I need but I think it can be modified quite easily (I don't know programming so it's a guess). What I need is one software that presses a key (right now only joystick is missing) while I talk (not voice recognition). With this kind of software people would be able to activate voice chats without pressing the key physically. I gave Squad game example because this game has 4 different voice chats: local, squad radio, leaders radio and direct communication to 1 leader. I would use this kind of feature to activate local chat to talk via voice to nearby players without pressing the key physically and it would be very useful during battle.

**Comment by ghost** [comment]
@Forsaken-Player As long as there is a hotkey/binding in place for changing your com channel, that is exactly what this does.

Are you having issues setting it up, if not would you like to close the issue?

**Comment by Forsaken-Player** [comment]
I couldn't find a way to configure that way. But to be honest I'm not gaming lately. Thank you for your interest and support.
